#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v27
# autospec commit: 65cf152
#
Name     : mm-common
Version  : 1.0.7
Release  : 11
URL      : https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.7.tar.xz
Source0  : https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.7.tar.xz
Summary  : mm-common's doctool build utilities for the GNOME C++ bindings
Group    : Development/Tools
License  : GPL-2.0
Requires: mm-common-bin = %{version}-%{release}
Requires: mm-common-data = %{version}-%{release}
Requires: mm-common-license = %{version}-%{release}
Requires: mm-common-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
skeletonmm is the C++ binding for the skeleton library.
This module is part of the GNOME C++ bindings effort <https://gtkmm.gnome.org/>.

%package bin
Summary: bin components for the mm-common package.
Group: Binaries
Requires: mm-common-data = %{version}-%{release}
Requires: mm-common-license = %{version}-%{release}

%description bin
bin components for the mm-common package.


%package data
Summary: data components for the mm-common package.
Group: Data

%description data
data components for the mm-common package.


%package dev
Summary: dev components for the mm-common package.
Group: Development
Requires: mm-common-bin = %{version}-%{release}
Requires: mm-common-data = %{version}-%{release}
Provides: mm-common-devel = %{version}-%{release}
Requires: mm-common = %{version}-%{release}

%description dev
dev components for the mm-common package.


%package doc
Summary: doc components for the mm-common package.
Group: Documentation
Requires: mm-common-man = %{version}-%{release}

%description doc
doc components for the mm-common package.


%package license
Summary: license components for the mm-common package.
Group: Default

%description license
license components for the mm-common package.


%package man
Summary: man components for the mm-common package.
Group: Default

%description man
man components for the mm-common package.


%prep
%setup -q -n mm-common-1.0.7
cd %{_builddir}/mm-common-1.0.7
pushd ..
cp -a mm-common-1.0.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749742001
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs
cd ../buildavx2;
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/mm-common
cp %{_builddir}/mm-common-%{version}/COPYING %{buildroot}/usr/share/package-licenses/mm-common/5b48b90e1bafdbede57b01227ade30d51f4b2a3c || :
cp %{_builddir}/mm-common-%{version}/skeletonmm/COPYING.tools %{buildroot}/usr/share/package-licenses/mm-common/5b48b90e1bafdbede57b01227ade30d51f4b2a3c || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mm-common-get
/usr/bin/mm-common-prepare

%files data
%defattr(-,root,root,-)
/usr/share/mm-common/build/check-dllexport-usage.py
/usr/share/mm-common/build/compile-binding.am
/usr/share/mm-common/build/dist-build-scripts.py
/usr/share/mm-common/build/dist-changelog.am
/usr/share/mm-common/build/dist-changelog.py
/usr/share/mm-common/build/doc-reference.am
/usr/share/mm-common/build/doc-reference.py
/usr/share/mm-common/build/generate-binding.am
/usr/share/mm-common/build/generate-binding.py
/usr/share/mm-common/doctags/libstdc++.tag
/usr/share/mm-common/doctool/doc-install.pl
/usr/share/mm-common/doctool/doc-postprocess.pl
/usr/share/mm-common/doctool/doc_install.py
/usr/share/mm-common/doctool/doc_postprocess.py
/usr/share/mm-common/doctool/doxygen-extra.css
/usr/share/mm-common/doctool/doxygen.css
/usr/share/mm-common/doctool/tagfile-to-devhelp2.xsl

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4
/usr/share/pkgconfig/mm-common-libstdc++.pc
/usr/share/pkgconfig/mm-common-util.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/mm\-common/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mm-common/5b48b90e1bafdbede57b01227ade30d51f4b2a3c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mm-common-get.1
/usr/share/man/man1/mm-common-prepare.1
