#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mm-common
Version  : 1.0.2
Release  : 1
URL      : https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.2.tar.xz
Source0  : https://download.gnome.org/sources/mm-common/1.0/mm-common-1.0.2.tar.xz
Summary  : mm-common's doctool build utilities for the GNOME C++ bindings
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: mm-common-bin = %{version}-%{release}
Requires: mm-common-data = %{version}-%{release}
Requires: mm-common-license = %{version}-%{release}
Requires: mm-common-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : sed

%description
This module is part of the GNOME C++ bindings effort <http://www.gtkmm.org/>.
The mm-common module provides the build infrastructure and utilities
shared among the GNOME C++ binding libraries.  It is only a required
dependency for building the C++ bindings from the gnome.org version
control repository.  An installation of mm-common is not required for
building tarball releases, unless configured to use maintainer-mode.

%package bin
Summary: bin components for the mm-common package.
Group: Binaries
Requires: mm-common-data = %{version}-%{release}
Requires: mm-common-license = %{version}-%{release}

%description bin
bin components for the mm-common package.


%package data
Summary: data components for the mm-common package.
Group: Data

%description data
data components for the mm-common package.


%package dev
Summary: dev components for the mm-common package.
Group: Development
Requires: mm-common-bin = %{version}-%{release}
Requires: mm-common-data = %{version}-%{release}
Provides: mm-common-devel = %{version}-%{release}
Requires: mm-common = %{version}-%{release}

%description dev
dev components for the mm-common package.


%package doc
Summary: doc components for the mm-common package.
Group: Documentation
Requires: mm-common-man = %{version}-%{release}

%description doc
doc components for the mm-common package.


%package license
Summary: license components for the mm-common package.
Group: Default

%description license
license components for the mm-common package.


%package man
Summary: man components for the mm-common package.
Group: Default

%description man
man components for the mm-common package.


%prep
%setup -q -n mm-common-1.0.2
cd %{_builddir}/mm-common-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1611158888
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mm-common
cp %{_builddir}/mm-common-1.0.2/COPYING %{buildroot}/usr/share/package-licenses/mm-common/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/mm-common-1.0.2/skeletonmm/COPYING %{buildroot}/usr/share/package-licenses/mm-common/9a1929f4700d2407c70b507b3b2aaf6226a9543c
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mm-common-get
/usr/bin/mm-common-prepare

%files data
%defattr(-,root,root,-)
/usr/share/mm-common/build/check-dllexport-usage.py
/usr/share/mm-common/build/compile-binding.am
/usr/share/mm-common/build/dist-build-scripts.py
/usr/share/mm-common/build/dist-changelog.am
/usr/share/mm-common/build/dist-changelog.py
/usr/share/mm-common/build/doc-reference.am
/usr/share/mm-common/build/doc-reference.py
/usr/share/mm-common/build/generate-binding.am
/usr/share/mm-common/build/generate-binding.py
/usr/share/mm-common/doctags/libstdc++.tag
/usr/share/mm-common/doctool/doc-install.pl
/usr/share/mm-common/doctool/doc-postprocess.pl
/usr/share/mm-common/doctool/doxygen-extra.css
/usr/share/mm-common/doctool/doxygen.css
/usr/share/mm-common/doctool/tagfile-to-devhelp2.xsl
/usr/share/pkgconfig/mm-common-libstdc++.pc
/usr/share/pkgconfig/mm-common-util.pc

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/mm\-common/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mm-common/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/mm-common/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mm-common-get.1
/usr/share/man/man1/mm-common-prepare.1
